name: Generate Snake

# This workflow runs every 6 hours to keep the snake up-to-date with your contributions
on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Generate the snake image from GitHub contributions graph
    - name: Generate Snake Contribution Graph
      uses: Platane/snk@v3
      id: snake
      with:
        github_user_name: ${{ github.repository_owner }}  # Use the current repo owner
        gif_out_path: dist/github-contribution-grid-snake.gif  # Output path for the gif
        svg_out_path: dist/github-contribution-grid-snake.svg  # Output path for the svg

    # 3. Push the generated files to the 'output' branch (keeping it separate from main)
    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output  # Push to the 'output' branch
        force: true

    # 4. Publish generated files to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output  # Branch where the images are saved
        build_dir: dist  # Directory containing the output files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
